name: Unit Tests
on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  test-server:
    name: Serverside unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install node packages
        run: |
          pnpm install --frozen-lockfile
        env:
          CI: true
      - name: Run tests on server
        working-directory: server/
        run: |
          pnpm test
        env:
          CI: true
